services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: ponp
      POSTGRES_PASSWORD: ponp
      POSTGRES_DB: ponp
    ports:
      - '54320:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  qstash:
    image: 'public.ecr.aws/upstash/qstash:latest'
    command: qstash dev
    ports:
      - '8080:8080'
  
volumes:
  postgres_data:
