services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: ponp
      POSTGRES_PASSWORD: ponp
      POSTGRES_DB: ponp
    ports:
      - '54321:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
