services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: ponp
      POSTGRES_PASSWORD: ponp
      POSTGRES_DB: ponp
    env_file:
      - path: .env.local
        required: false
    ports:
      - '${POSTGRES_PORT:-54320}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  qstash:
    image: 'public.ecr.aws/upstash/qstash:latest'
    command: qstash dev
    env_file:
      - path: .env.local
        required: false
    ports:
      - '${QSTASH_PORT:-8080}:8080'
  
volumes:
  postgres_data:
