blank_issues_enabled: true
contact_links:
  - name: 仕様書
    url: https://github.com/yukun-web/PrAhaChallengeOnPrAhaChallenge/blob/main/docs/仕様書.md
    about: 機能仕様を確認する
  - name: コーディング規約
    url: https://github.com/yukun-web/PrAhaChallengeOnPrAhaChallenge/blob/main/docs/コーディング規約.md
    about: コーディング規約を確認する
  - name: 開発運用ガイド
    url: https://github.com/yukun-web/PrAhaChallengeOnPrAhaChallenge/blob/main/docs/開発運用ガイド.md
    about: 開発運用ルールを確認する
